CREATE DATABASE SoftUni

CREATE TABLE Towns
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) NOT NULL
)

CREATE TABLE Addresses
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
AddressText VARCHAR(200) NOT NULL,
TownId INT NOT NULL
)

ALTER TABLE Addresses
ADD FOREIGN KEY (TownId) REFERENCES Towns(Id)

CREATE TABLE Departments
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
Name VARCHAR(200) NOT NULL
)

CREATE TABLE Employees
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL,
JobTitle VARCHAR(100) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATETIME NOT NULL,
Salary DECIMAL(15,2) NOT NULL,
AddressId INT NOT NULL
)

ALTER TABLE Employees
ADD FOREIGN KEY (DepartmentId) REFERENCES Departments(Id)

ALTER TABLE Employees
ADD FOREIGN KEY (AddressId) REFERENCES Addresses(Id)